import type { GardenCatalogItem } from "./types";

export const GARDEN_CATALOG = {
  flower_pink: {
    id: "flower_pink",
    name: "恩典花",
    kind: "plant",
    footprint: { width: 1, height: 1 },
    hitWidth: 54,
    hitHeight: 72,
    blocksPlacement: true,
    draggable: true,
    rotationMode: "none",
    renderVariant: "pink-flower",
    growth: {
      stageThresholdsMs: [0, 20_000, 60_000, 120_000],
      waterBoostMs: 15_000,
      harvestReward: 12,
    },
  },
  olive_tree: {
    id: "olive_tree",
    name: "平安樹（待新素材）",
    kind: "tree",
    footprint: { width: 2, height: 2 },
    hitWidth: 156,
    hitHeight: 286,
    blocksPlacement: true,
    draggable: true,
    rotationMode: "none",
    renderVariant: "olive-tree",
  },
  wooden_bench: {
    id: "wooden_bench",
    name: "同行長椅（舊版）",
    kind: "bench",
    footprint: { width: 2, height: 1 },
    hitWidth: 108,
    hitHeight: 76,
    blocksPlacement: true,
    draggable: true,
    rotationMode: "two-way",
    renderVariant: "wooden-bench",
  },
  flower_bench: {
    id: "flower_bench",
    name: "童話花園長椅",
    kind: "decoration",
    footprint: { width: 3, height: 1 },
    hitWidth: 250,
    hitHeight: 260,
    blocksPlacement: true,
    draggable: true,
    rotationMode: "none",
    renderVariant: "garden-bench",
    spriteId: "garden_bench",
  },
  grace_fountain: {
    id: "grace_fountain",
    name: "恩典活水泉",
    kind: "fountain",
    footprint: { width: 4, height: 4 },
    hitWidth: 400,
    hitHeight: 405,
    blocksPlacement: true,
    draggable: false,
    rotationMode: "none",
    renderVariant: "grace-fountain",
    spriteId: "grace_fountain",
  },
  flower_well: {
    id: "flower_well",
    name: "恩霖水井",
    kind: "decoration",
    footprint: { width: 3, height: 2 },
    hitWidth: 270,
    hitHeight: 378,
    blocksPlacement: true,
    draggable: true,
    rotationMode: "none",
    renderVariant: "garden-well",
    spriteId: "garden_well",
  },
  grace_lamp: {
    id: "grace_lamp",
    name: "盼望燈",
    kind: "lamp",
    footprint: { width: 1, height: 1 },
    hitWidth: 92,
    hitHeight: 344,
    blocksPlacement: true,
    draggable: true,
    rotationMode: "none",
    renderVariant: "garden-lamp",
    spriteId: "garden_lamp",
  },
  flower_arch: {
    id: "flower_arch",
    name: "恩典花拱門",
    kind: "decoration",
    footprint: { width: 3, height: 2 },
    hitWidth: 280,
    hitHeight: 382,
    blocksPlacement: true,
    draggable: true,
    rotationMode: "none",
    renderVariant: "garden-arch",
    spriteId: "garden_arch",
  },
  flower_hammock: {
    id: "flower_hammock",
    name: "花藤吊床",
    kind: "decoration",
    footprint: { width: 4, height: 2 },
    hitWidth: 390,
    hitHeight: 325,
    blocksPlacement: true,
    draggable: true,
    rotationMode: "none",
    renderVariant: "garden-hammock",
    spriteId: "garden_hammock",
  },
  flower_hammock_grounded: {
    id: "flower_hammock_grounded",
    name: "花藤吊床（舊存檔兼容）",
    kind: "decoration",
    footprint: { width: 4, height: 2 },
    hitWidth: 390,
    hitHeight: 325,
    blocksPlacement: true,
    draggable: true,
    rotationMode: "none",
    renderVariant: "garden-hammock",
    spriteId: "garden_hammock",
  },
  white_flower_fence: {
    id: "white_flower_fence",
    name: "白色花藤圍欄",
    kind: "decoration",
    footprint: { width: 4, height: 1 },
    hitWidth: 310,
    hitHeight: 244,
    blocksPlacement: true,
    draggable: true,
    rotationMode: "none",
    renderVariant: "garden-fence",
    spriteId: "garden_fence",
  },
  garden_cafe_set: {
    id: "garden_cafe_set",
    name: "花園陽傘桌椅",
    kind: "decoration",
    footprint: { width: 3, height: 3 },
    hitWidth: 305,
    hitHeight: 365,
    blocksPlacement: true,
    draggable: true,
    rotationMode: "none",
    renderVariant: "garden-patio-set",
    spriteId: "garden_patio_set",
  },
  default_avatar: {
    id: "default_avatar",
    name: "花園同行者",
    kind: "avatar",
    footprint: { width: 1, height: 1 },
    hitWidth: 54,
    hitHeight: 112,
    blocksPlacement: false,
    draggable: true,
    rotationMode: "none",
    renderVariant: "default-avatar",
  },
} as const satisfies Record<string, GardenCatalogItem>;

export type GardenCatalogId = keyof typeof GARDEN_CATALOG;

export function getCatalogItem(catalogId: string): GardenCatalogItem | null {
  return (GARDEN_CATALOG as Record<string, GardenCatalogItem>)[catalogId] ?? null;
}
